### ISSUE TITLE
JSON Schema does not identify $schema

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/vr-spec#170] opened 2019-11-04 14:32 UTC
The documentation notes that the schemas provided are in draft-7, however the schema documents themselves do not identify as being draft-7.

It should have a $schema value of `http://json-schema.org/draft-07/schema#`.
the "latest" URI is going away, as this casues problems, for example now we have released draft 2019-09 (formally draft-8), such a latest link would point to a different version than the one intended.

Happy to fix this if it's welcome.

**Comment by larrybabb** [comment] 2019-11-04 15:11
I think a PR would be welcome, @Relequestual . I'll defer to @reece for the final word.

**Comment by reece** [comment] 2019-11-04 18:02
@Relequestual : I would welcome all advice you might have. More generally, it would be great to work together on tools and techniques that we can share with GA4GH so that we all do this one way.

My goals were to make all of these work together, which is a tall order given that json-schema, openapi, and python support for these are all in flux. From your repos, I see that you've also delved into getting json-schema work in python, with python-jsonschema-objects, and with OpenAPI.

The schema is defined as `"$schema": "http://json-schema.org/schema#"`. My memory is vague, but I think I did this because it was the only way I could get it to work with all of the tools I was using (at the time -- things might be better now!).

VR was intended to be used in at least two contexts:
* building, parsing, and serializing models using python-jsonschema-objects
* build a REST interface using connexion with an API defined by OpenAPI 3.0

See the `8-rest-service` branch for current wip. I'm unsure whether it's functional right now.

Again, I'd be thrilled to hear any tips you have about how to improve!

**Comment by reece** [comment] 2019-12-26 14:56
Fixed in 9f0e05dc1f4f48b84267fe9d2c00254ac50c4dc9. 
For now, set as draft-4 because later versions are not supported by python-jsonschema-objects
(https://github.com/cwacek/python-jsonschema-objects/blob/master/python_jsonschema_objects/__init__.py#L27)

**Closed by reece** 2019-12-26 14:56 UTC
